name: Tests

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        haxe: [4.0.5, 4.1.5, 4.2.5]

    steps:
    - uses: actions/checkout@v1

    - name: Setup haxe ${{ matrix.haxe }}
      uses: krdlab/setup-haxe@v1
      with:
        haxe-version: ${{ matrix.haxe }}

    - name: Install libs
      run: |
        npm install
        haxelib install buddy
        haxelib install enzyme
        haxelib install react
        haxelib install hxnodejs

    - name: Run tests
      run: |
        npm run test

    - name: Run tests (React)
      run: |
        npm run test:react
